_definitions:
  messages:
    version_fmt: &ver_fmt "Specify CLI version: [bold cyan]{version}[/bold cyan]"

name: version
handler: specify_cli.commands.version:version
help: "Show version information."
messages:
  output_format: *ver_fmt
