project:
  version: "0.0.23"
  python: "3.11"
  node: "22"

docker:
  base_image: "mcr.microsoft.com/devcontainers/python:1-3.11-bookworm"

dependencies:
  system:
    git: "1.3.4"
    uv: "latest"
    docker_buildx: "latest"
    eslint: "latest"
    gcm: "2.6.1"

  features:
    git: "1.3.4"
    docker_in_docker: "2.12.4"
    github_cli: "1.0.15"
    common_utils: "2.5.4"
    python: "1.7.1"
    powershell: "1.5.1"
    nvidia_cuda: "2.0.0"
    node: "1.6.0"

  python:
    typer: "latest"
    rich: "latest"
    httpx: "latest"
    platformdirs: "latest"
    readchar: "latest"
    truststore: ">=0.10.4"
